-- GMC Geology Department Welfare v1.0.3
-- Run this in Supabase SQL Editor to enable Member/Admin Messages.
-- Assumes public.is_admin() already exists from initial setup.

create table if not exists public.messages (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists messages_select on public.messages;
drop policy if exists messages_member_insert on public.messages;
drop policy if exists messages_admin_insert on public.messages;
drop policy if exists messages_admin_update on public.messages;
drop policy if exists messages_member_update_read on public.messages;
drop policy if exists messages_admin_delete on public.messages;

create policy messages_select
on public.messages
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.users u
    where u.id = auth.uid()::text
      and (
        u.data->>'memberDocId' = messages.data->>'memberDocId'
        or u.data->>'memberId' = messages.data->>'memberId'
        or lower(coalesce(messages.data->>'memberEmail','')) = lower(auth.email())
      )
  )
);

-- Members can create their own tickets.
create policy messages_member_insert
on public.messages
for insert
to authenticated
with check (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()::text
      and coalesce(u.data->>'role','member') = 'member'
      and (
        u.data->>'memberDocId' = messages.data->>'memberDocId'
        or u.data->>'memberId' = messages.data->>'memberId'
        or lower(coalesce(messages.data->>'memberEmail','')) = lower(auth.email())
      )
  )
);

-- Admin can create if needed.
create policy messages_admin_insert
on public.messages
for insert
to authenticated
with check (public.is_admin());

-- Admin can reply, set status, delete attachment metadata, etc.
create policy messages_admin_update
on public.messages
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Members can mark their own message as read from their portal.
create policy messages_member_update_read
on public.messages
for update
to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()::text
      and (
        u.data->>'memberDocId' = messages.data->>'memberDocId'
        or u.data->>'memberId' = messages.data->>'memberId'
        or lower(coalesce(messages.data->>'memberEmail','')) = lower(auth.email())
      )
  )
)
with check (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()::text
      and (
        u.data->>'memberDocId' = messages.data->>'memberDocId'
        or u.data->>'memberId' = messages.data->>'memberId'
        or lower(coalesce(messages.data->>'memberEmail','')) = lower(auth.email())
      )
  )
);

create policy messages_admin_delete
on public.messages
for delete
to authenticated
using (public.is_admin());

-- Private storage bucket for member attachments.
insert into storage.buckets (id, name, public)
values ('message-attachments', 'message-attachments', false)
on conflict (id) do nothing;

drop policy if exists message_attachments_read on storage.objects;
drop policy if exists message_attachments_insert on storage.objects;
drop policy if exists message_attachments_update on storage.objects;
drop policy if exists message_attachments_delete on storage.objects;

-- Authenticated users can open signed URLs generated by the app.
create policy message_attachments_read
on storage.objects
for select
to authenticated
using (bucket_id = 'message-attachments');

-- Members/admins may upload, but the app enforces: JPG/PNG/PDF/DOC/DOCX only, 5MB per file, 3 files per message, 15MB total.
create policy message_attachments_insert
on storage.objects
for insert
to authenticated
with check (bucket_id = 'message-attachments');

create policy message_attachments_update
on storage.objects
for update
to authenticated
using (bucket_id = 'message-attachments' and public.is_admin())
with check (bucket_id = 'message-attachments' and public.is_admin());

-- Admin can delete member attachments to save storage.
create policy message_attachments_delete
on storage.objects
for delete
to authenticated
using (bucket_id = 'message-attachments' and public.is_admin());
